# Generated by Django 4.0.2 on 2022-03-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dambase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blockquote_authorname',
        ),
    ]
