# Generated by Django 4.0.2 on 2022-03-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dambase', '0002_remove_post_blockquote_authorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blockquote_thename',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
